# Generated by Django 3.2.5 on 2021-08-04 12:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_userdisplayname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDisplayname',
            new_name='user_name',
        ),
    ]
