# Generated by Django 3.2.5 on 2021-08-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_report_report_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(max_length=150),
        ),
    ]
